// <auto-generated />

using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Query;
using Microsoft.Crm.Sdk.Messages;
using Microsoft.Xrm.Sdk.Messages;
using Microsoft.Xrm.Sdk.Metadata;
using Microsoft.Xrm.Sdk.Client;
using System.Threading.Tasks;
using System.ComponentModel;

namespace AlexanderDevelopment.ConfigDataMover.Lib.ProxyClasses
{
    [EntityLogicalNameAttribute("sdkmessageprocessingstep")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XrmToolkit", "4.0")]
    public partial class sdkmessageprocessingstep : BaseProxyClass
    {
        public new const string LogicalName = "sdkmessageprocessingstep";
        public const int ObjectTypeCode = 4608;
        public const string PrimaryIdAttribute = "sdkmessageprocessingstepid";
        public const string PrimaryNameAttribute = "name";
        
        static sdkmessageprocessingstep()
        {
            BaseProxyClass.RegisterProxyType(typeof(sdkmessageprocessingstep), "sdkmessageprocessingstep");
            _textOptions = new Dictionary<string, eTextOptions>();
            _numberOptions = new Dictionary<string, eNumberOptions>();
            _errorStrings = new Dictionary<string, string>();
            TextError = "The value for attribute '{0}' cannot be longer than {3} characters. The length of the value is {2} characters.";
            NumberError = "The value for attribute '{0}' must be between {2} and {3}. The value is {1}";
        }
        public sdkmessageprocessingstep() : base(new Entity("sdkmessageprocessingstep")) { }
        public sdkmessageprocessingstep(Entity original) : base(original) { }
        public static string GetLogicalName() { return BaseProxyClass.GetLogicalName<sdkmessageprocessingstep>(); }
        /// <summary>
        /// Action to perform when the string value is greater than the allowed length.
        /// <para>This is the default for any string attribute in this Entity</para>
        /// </summary>
        public static eTextOptions TextOptions { get; set; }
        private static Dictionary<string, eTextOptions> _textOptions;
        /// <summary>
        /// Use this to set an action and error string when a value is greater than the allowed length
        /// </summary>
        /// <param name="logicalName">Name of Attribute</param>
        /// <param name="options">Action to perform when the value is greater than the allowed length</param>
        /// <param name="errorString">Optional: Error to throw if the eTextOptions == ThrowError
        /// <para>If nothing is specified then the 'TextError' string is used.</para>
        /// <para>You may use the following parameters:</para>
        /// <para>{0} = Attribute Logical Name</para>
        /// <para>{1} = Value</para>
        /// <para>{2} = Length</para>
        /// <para>{3} = Max Length</para>
        /// </param>
        public static void SetTextOptions(string logicalName, eTextOptions options, string errorString = null)
        {
            if (_textOptions.ContainsKey(logicalName)) { _textOptions[logicalName] = options; }
            else { _textOptions.Add(logicalName, options); }
            if (!string.IsNullOrEmpty(errorString))
            {
                if (_errorStrings.ContainsKey(logicalName)) { _errorStrings[logicalName] = errorString; }
                else { _errorStrings.Add(logicalName, errorString); }
            }
            else if (_errorStrings.ContainsKey(logicalName)) { _errorStrings.Remove(logicalName); }
        }
        protected override eTextOptions GetTextOptions(string logicalName)
        {
            if (_textOptions.ContainsKey(logicalName)) { return _textOptions[logicalName]; }
            return TextOptions;
        }
        /// <summary>
        /// Action to perform when the number value is greater or less than the allowed value.
        /// <para>This is the default for any int, decimal, double, or money attribute in this Entity</para>
        /// </summary>
        public static eNumberOptions NumberOptions { get; set; }
        private static Dictionary<string, eNumberOptions> _numberOptions;
        /// <summary>
        /// Use this to set an action and error string when a value is greater or less than the allowed value
        /// </summary>
        /// <param name="logicalName">Name of Attribute</param>
        /// <param name="options">Action to perform when the value is greater or less than the allowed value</param>
        /// <param name="errorString">Optional: Error to throw if the eNumberOptions == ThrowError
        /// <para>If nothing is specified then the 'NumberError' string is used.</para>
        /// <para>You may use the following parameters:</para>
        /// <para>{0} = Attribute Logical Name</para>
        /// <para>{1} = Value</para>
        /// <para>{2} = Min Value</para>
        /// <para>{3} = Max Value</para>
        /// </param>
        public static void SetNumberOptions(string logicalName, eNumberOptions options, string errorString = null)
        {
            if (_numberOptions.ContainsKey(logicalName)) { _numberOptions[logicalName] = options; }
            else { _numberOptions.Add(logicalName, options); }
            if (!string.IsNullOrEmpty(errorString))
            {
                if (_errorStrings.ContainsKey(logicalName)) { _errorStrings[logicalName] = errorString; }
                else { _errorStrings.Add(logicalName, errorString); }
            }
            else if (_errorStrings.ContainsKey(logicalName)) { _errorStrings.Remove(logicalName); }
        }
        protected override eNumberOptions GetNumberOptions(string logicalName)
        {
            if (_numberOptions.ContainsKey(logicalName)) { return _numberOptions[logicalName]; }
            return NumberOptions;
        }
        private static Dictionary<string, string> _errorStrings;
        protected override string GetErrorString(string attributeName, BaseProxyClass.eErrorType defaultErrorType)
        {
            if (_errorStrings.ContainsKey(attributeName))
            {
                return _errorStrings[attributeName];
            }
            return defaultErrorType == BaseProxyClass.eErrorType.Text ? TextError : NumberError;
        }
        /// <summary>
        /// <para>Default error string is: The value for attribute '{0}' cannot be longer than {3} characters. The length of the value is {2} characters.</para>
        /// <para>You may use the following parameters</para>
        /// <para>{0} = Attribute Name</para>
        /// <para>{1} = Value</para>
        /// <para>{2} = Length</para>
        /// <para>{3} = Max Length</para>
        /// </summary>
        public static string TextError { get; set; }
        /// <summary>
        /// <para>Default error string is: The value for attribute '{0}' must be between {2} and {3}. The value is {1}.</para>
        /// <para>You may use the following parameters</para>
        /// <para>{0} = Attribute Name</para>
        /// <para>{1} = Value</para>
        /// <para>{2} = Min Value</para>
        /// <para>{3} = Max Value</para>
        /// </summary>
        public static string NumberError { get; set; }

        ///<summary>
///<para>Logical Name: createdonbehalfbyyominame</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("createdonbehalfbyyominame")]
public string createdonbehalfbyyominame
{
	get { return this.GetPropertyValue<string>("createdonbehalfbyyominame"); }
}
///<summary>
///<para>Logical Name: eventhandlertypecode</para>
///</summary>
[AttributeLogicalNameAttribute("eventhandlertypecode")]
public string eventhandlertypecode
{
	get { return this.GetPropertyValue<string>("eventhandlertypecode"); }
	set { this.SetPropertyValue<string>("eventhandlertypecode", value, "eventhandlertypecode"); }
}
///<summary>
///<para>Logical Name: eventhandlername</para>
///<para>Max Length: 256 characters</para>
///</summary>
[AttributeLogicalNameAttribute("eventhandlername")]
public string eventhandlername
{
	get { return this.GetPropertyValue<string>("eventhandlername"); }
}
///<summary>
///<para>Logical Name: impersonatinguseridname</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("impersonatinguseridname")]
public string impersonatinguseridname
{
	get { return this.GetPropertyValue<string>("impersonatinguseridname"); }
}
///<summary>
///<para>Logical Name: customizationlevel</para>
///<para>Minimum Value: -255</para>
///<para>Maximum Value: 255</para>
///</summary>
[AttributeLogicalNameAttribute("customizationlevel")]
public int? customizationlevel
{
	get { return this.GetPropertyValue<int?>("customizationlevel"); }
}
///<summary>
///<para>Logical Name: modifiedbyname</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("modifiedbyname")]
public string modifiedbyname
{
	get { return this.GetPropertyValue<string>("modifiedbyname"); }
}
///<summary>
///<para>Logical Name: versionnumber</para>
///</summary>
[AttributeLogicalNameAttribute("versionnumber")]
public int? versionnumber
{
	get { return this.GetPropertyValue<int?>("versionnumber"); }
}
///<summary>
///<para>Key Property (Uniqueidentifier)</para>
///<para>Logical Name: sdkmessageprocessingstepid</para>
///</summary>
[AttributeLogicalNameAttribute("sdkmessageprocessingstepid")]
public Guid sdkmessageprocessingstepid
{
	get
	{
		return this.Id;
	}
	set
	{
		this.Id = value;
	}
}
///<summary>
///<para>Logical Name: sdkmessageidname</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("sdkmessageidname")]
public string sdkmessageidname
{
	get { return this.GetPropertyValue<string>("sdkmessageidname"); }
}
///<summary>
///<para>Logical Name: createdbyname</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("createdbyname")]
public string createdbyname
{
	get { return this.GetPropertyValue<string>("createdbyname"); }
}
///<summary>
///<para>Logical Name: modifiedonbehalfbyyominame</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("modifiedonbehalfbyyominame")]
public string modifiedonbehalfbyyominame
{
	get { return this.GetPropertyValue<string>("modifiedonbehalfbyyominame"); }
}
///<summary>
///<para>Logical Name: organizationid</para>
///</summary>
[AttributeLogicalNameAttribute("organizationid")]
public EntityReference organizationid
{
	get { return this.GetPropertyValue<EntityReference>("organizationid"); }
}
///<summary>
///<para>Logical Name: createdonbehalfbyname</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("createdonbehalfbyname")]
public string createdonbehalfbyname
{
	get { return this.GetPropertyValue<string>("createdonbehalfbyname"); }
}
///<summary>
///<para>Logical Name: sdkmessageprocessingstepidunique</para>
///</summary>
[AttributeLogicalNameAttribute("sdkmessageprocessingstepidunique")]
public Guid sdkmessageprocessingstepidunique
{
	get { return this.GetPropertyValue<Guid>("sdkmessageprocessingstepidunique"); }
}
///<summary>
///<para>Logical Name: modifiedonbehalfbyname</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("modifiedonbehalfbyname")]
public string modifiedonbehalfbyname
{
	get { return this.GetPropertyValue<string>("modifiedonbehalfbyname"); }
}
///<summary>
///<para>Logical Name: plugintypeidname</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("plugintypeidname")]
public string plugintypeidname
{
	get { return this.GetPropertyValue<string>("plugintypeidname"); }
}
///<summary>
///<para>Logical Name: asyncautodelete</para>
///<para>True = Yes</para>
///<para>False = No</para>
///</summary>
[AttributeLogicalNameAttribute("asyncautodelete")]
public bool? asyncautodelete
{
	get { return this.GetPropertyValue<bool?>("asyncautodelete"); }
	set { this.SetPropertyValue<bool?>("asyncautodelete", value, "asyncautodelete"); }
}
/// <summary>
///Logical Name: componentstate
/// </summary>
[AttributeLogicalNameAttribute("componentstate")]
public eComponentState? componentstate
{
	get
	{
		if (componentstate_OptionSetValue != null) { return (eComponentState)componentstate_OptionSetValue.Value; }
		return null;
	}
}
///<summary>
///<para>Logical Name: componentstate</para>
///</summary>
[AttributeLogicalNameAttribute("componentstate")]
public OptionSetValue componentstate_OptionSetValue
{
	get { return this.GetPropertyValue<OptionSetValue>("componentstate"); }
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="Service">CRM Organization Service</param>
/// <returns></returns>
public string componentstate_Text(IOrganizationService Service)
{
	return this.componentstate_OptionSetValue.GetOptionSetText(Service, this, "componentstate");
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
/// <returns></returns>
public string componentstate_Text(EnumAttributeMetadata AttributeMetadata)
{
	return AttributeMetadata.GetOptionSetText(this.componentstate_OptionSetValue.Value);
}
///<summary>
///<para>Logical Name: configuration</para>
///<para>Max Length: 1073741823 characters</para>
///</summary>
[AttributeLogicalNameAttribute("configuration")]
public string configuration
{
	get { return this.GetPropertyValue<string>("configuration"); }
	set { this.SetPropertyValue("configuration", value, 1073741823, "configuration"); }
}
///<summary>
///<para>Logical Name: createdby</para>
///</summary>
[AttributeLogicalNameAttribute("createdby")]
public EntityReference createdby
{
	get { return this.GetPropertyValue<EntityReference>("createdby"); }
}
///<summary>
///<para>Logical Name: createdonbehalfby</para>
///</summary>
[AttributeLogicalNameAttribute("createdonbehalfby")]
public EntityReference createdonbehalfby
{
	get { return this.GetPropertyValue<EntityReference>("createdonbehalfby"); }
}
///<summary>
///<para>Logical Name: createdon</para>
///</summary>
[AttributeLogicalNameAttribute("createdon")]
public DateTime? createdon
{
	get { return this.GetPropertyValue<DateTime?>("createdon"); }
}
///<summary>
///<para>Logical Name: iscustomizable</para>
///</summary>
[AttributeLogicalNameAttribute("iscustomizable")]
public BooleanManagedProperty iscustomizable
{
	get { return this.GetPropertyValue<BooleanManagedProperty>("iscustomizable"); }
	set { this.SetPropertyValue<BooleanManagedProperty>("iscustomizable", value, "iscustomizable"); }
}
/// <summary>
///Logical Name: supporteddeployment
/// </summary>
[AttributeLogicalNameAttribute("supporteddeployment")]
public eSupportedDeployment? supporteddeployment
{
	get
	{
		if (supporteddeployment_OptionSetValue != null) { return (eSupportedDeployment)supporteddeployment_OptionSetValue.Value; }
		return null;
	}
	set
	{
		if (value != null) { this.supporteddeployment_OptionSetValue = new OptionSetValue((int)value); }
		else this.supporteddeployment_OptionSetValue = null;
	}
}
///<summary>
///<para>Logical Name: supporteddeployment</para>
///</summary>
[AttributeLogicalNameAttribute("supporteddeployment")]
public OptionSetValue supporteddeployment_OptionSetValue
{
	get { return this.GetPropertyValue<OptionSetValue>("supporteddeployment"); }
	set { this.SetPropertyValue<OptionSetValue>("supporteddeployment", value, "supporteddeployment_OptionSetValue"); }
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="Service">CRM Organization Service</param>
/// <returns></returns>
public string supporteddeployment_Text(IOrganizationService Service)
{
	return this.supporteddeployment_OptionSetValue.GetOptionSetText(Service, this, "supporteddeployment");
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
/// <returns></returns>
public string supporteddeployment_Text(EnumAttributeMetadata AttributeMetadata)
{
	return AttributeMetadata.GetOptionSetText(this.supporteddeployment_OptionSetValue.Value);
}
///<summary>
///<para>Logical Name: description</para>
///<para>Max Length: 256 characters</para>
///</summary>
[AttributeLogicalNameAttribute("description")]
public string description
{
	get { return this.GetPropertyValue<string>("description"); }
	set { this.SetPropertyValue("description", value, 256, "description"); }
}
///<summary>
///<para>Logical Name: eventhandler</para>
///</summary>
[AttributeLogicalNameAttribute("eventhandler")]
public EntityReference eventhandler
{
	get { return this.GetPropertyValue<EntityReference>("eventhandler"); }
	set { this.SetPropertyValue<EntityReference>("eventhandler", value, "eventhandler"); }
}
/// <summary>
///Logical Name: mode
/// </summary>
[AttributeLogicalNameAttribute("mode")]
public eMode? mode
{
	get
	{
		if (mode_OptionSetValue != null) { return (eMode)mode_OptionSetValue.Value; }
		return null;
	}
	set
	{
		if (value != null) { this.mode_OptionSetValue = new OptionSetValue((int)value); }
		else this.mode_OptionSetValue = null;
	}
}
///<summary>
///<para>Logical Name: mode</para>
///</summary>
[AttributeLogicalNameAttribute("mode")]
public OptionSetValue mode_OptionSetValue
{
	get { return this.GetPropertyValue<OptionSetValue>("mode"); }
	set { this.SetPropertyValue<OptionSetValue>("mode", value, "mode_OptionSetValue"); }
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="Service">CRM Organization Service</param>
/// <returns></returns>
public string mode_Text(IOrganizationService Service)
{
	return this.mode_OptionSetValue.GetOptionSetText(Service, this, "mode");
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
/// <returns></returns>
public string mode_Text(EnumAttributeMetadata AttributeMetadata)
{
	return AttributeMetadata.GetOptionSetText(this.mode_OptionSetValue.Value);
}
///<summary>
///<para>Logical Name: rank</para>
///<para>Minimum Value: -2147483648</para>
///<para>Maximum Value: 2147483647</para>
///</summary>
[AttributeLogicalNameAttribute("rank")]
public int? rank
{
	get { return this.GetPropertyValue<int?>("rank"); }
	set { this.SetPropertyValue("rank", (int?)value, (int)-2147483648, (int)2147483647, "rank"); }
}
/// <summary>
///Logical Name: stage
/// </summary>
[AttributeLogicalNameAttribute("stage")]
public eStage? stage
{
	get
	{
		if (stage_OptionSetValue != null) { return (eStage)stage_OptionSetValue.Value; }
		return null;
	}
	set
	{
		if (value != null) { this.stage_OptionSetValue = new OptionSetValue((int)value); }
		else this.stage_OptionSetValue = null;
	}
}
///<summary>
///<para>Logical Name: stage</para>
///</summary>
[AttributeLogicalNameAttribute("stage")]
public OptionSetValue stage_OptionSetValue
{
	get { return this.GetPropertyValue<OptionSetValue>("stage"); }
	set { this.SetPropertyValue<OptionSetValue>("stage", value, "stage_OptionSetValue"); }
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="Service">CRM Organization Service</param>
/// <returns></returns>
public string stage_Text(IOrganizationService Service)
{
	return this.stage_OptionSetValue.GetOptionSetText(Service, this, "stage");
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
/// <returns></returns>
public string stage_Text(EnumAttributeMetadata AttributeMetadata)
{
	return AttributeMetadata.GetOptionSetText(this.stage_OptionSetValue.Value);
}
///<summary>
///<para>Logical Name: filteringattributes</para>
///<para>Max Length: 100000 characters</para>
///</summary>
[AttributeLogicalNameAttribute("filteringattributes")]
public string filteringattributes
{
	get { return this.GetPropertyValue<string>("filteringattributes"); }
	set { this.SetPropertyValue("filteringattributes", value, 100000, "filteringattributes"); }
}
///<summary>
///<para>Logical Name: ishidden</para>
///</summary>
[AttributeLogicalNameAttribute("ishidden")]
public BooleanManagedProperty ishidden
{
	get { return this.GetPropertyValue<BooleanManagedProperty>("ishidden"); }
	set { this.SetPropertyValue<BooleanManagedProperty>("ishidden", value, "ishidden"); }
}
///<summary>
///<para>Logical Name: impersonatinguserid</para>
///</summary>
[AttributeLogicalNameAttribute("impersonatinguserid")]
public EntityReference impersonatinguserid
{
	get { return this.GetPropertyValue<EntityReference>("impersonatinguserid"); }
	set { this.SetPropertyValue<EntityReference>("impersonatinguserid", value, "impersonatinguserid"); }
}
///<summary>
///<para>Logical Name: canusereadonlyconnection</para>
///<para>True = Yes</para>
///<para>False = No</para>
///</summary>
[AttributeLogicalNameAttribute("canusereadonlyconnection")]
public bool? canusereadonlyconnection
{
	get { return this.GetPropertyValue<bool?>("canusereadonlyconnection"); }
	set { this.SetPropertyValue<bool?>("canusereadonlyconnection", value, "canusereadonlyconnection"); }
}
///<summary>
///<para>Logical Name: introducedversion</para>
///<para>Max Length: 48 characters</para>
///</summary>
[AttributeLogicalNameAttribute("introducedversion")]
public string introducedversion
{
	get { return this.GetPropertyValue<string>("introducedversion"); }
	set { this.SetPropertyValue("introducedversion", value, 48, "introducedversion"); }
}
/// <summary>
///Logical Name: invocationsource
/// </summary>
[AttributeLogicalNameAttribute("invocationsource")]
public eInvocationSource? invocationsource
{
	get
	{
		if (invocationsource_OptionSetValue != null) { return (eInvocationSource)invocationsource_OptionSetValue.Value; }
		return null;
	}
	set
	{
		if (value != null) { this.invocationsource_OptionSetValue = new OptionSetValue((int)value); }
		else this.invocationsource_OptionSetValue = null;
	}
}
///<summary>
///<para>Logical Name: invocationsource</para>
///</summary>
[AttributeLogicalNameAttribute("invocationsource")]
public OptionSetValue invocationsource_OptionSetValue
{
	get { return this.GetPropertyValue<OptionSetValue>("invocationsource"); }
	set { this.SetPropertyValue<OptionSetValue>("invocationsource", value, "invocationsource_OptionSetValue"); }
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="Service">CRM Organization Service</param>
/// <returns></returns>
public string invocationsource_Text(IOrganizationService Service)
{
	return this.invocationsource_OptionSetValue.GetOptionSetText(Service, this, "invocationsource");
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
/// <returns></returns>
public string invocationsource_Text(EnumAttributeMetadata AttributeMetadata)
{
	return AttributeMetadata.GetOptionSetText(this.invocationsource_OptionSetValue.Value);
}
///<summary>
///<para>Logical Name: modifiedby</para>
///</summary>
[AttributeLogicalNameAttribute("modifiedby")]
public EntityReference modifiedby
{
	get { return this.GetPropertyValue<EntityReference>("modifiedby"); }
}
///<summary>
///<para>Logical Name: modifiedonbehalfby</para>
///</summary>
[AttributeLogicalNameAttribute("modifiedonbehalfby")]
public EntityReference modifiedonbehalfby
{
	get { return this.GetPropertyValue<EntityReference>("modifiedonbehalfby"); }
}
///<summary>
///<para>Logical Name: modifiedon</para>
///</summary>
[AttributeLogicalNameAttribute("modifiedon")]
public DateTime? modifiedon
{
	get { return this.GetPropertyValue<DateTime?>("modifiedon"); }
}
///<summary>
///<para>Logical Name: name</para>
///<para>Max Length: 256 characters</para>
///</summary>
[AttributeLogicalNameAttribute("name")]
public string name
{
	get { return this.GetPropertyValue<string>("name"); }
	set { this.SetPropertyValue("name", value, 256, "name"); }
}
///<summary>
///<para>Logical Name: plugintypeid</para>
///</summary>
[AttributeLogicalNameAttribute("plugintypeid")]
public EntityReference plugintypeid
{
	get { return this.GetPropertyValue<EntityReference>("plugintypeid"); }
	set { this.SetPropertyValue<EntityReference>("plugintypeid", value, "plugintypeid"); }
}
///<summary>
///<para>Logical Name: overwritetime</para>
///</summary>
[AttributeLogicalNameAttribute("overwritetime")]
public DateTime? overwritetime
{
	get { return this.GetPropertyValue<DateTime?>("overwritetime"); }
}
///<summary>
///<para>Logical Name: sdkmessageid</para>
///</summary>
[AttributeLogicalNameAttribute("sdkmessageid")]
public EntityReference sdkmessageid
{
	get { return this.GetPropertyValue<EntityReference>("sdkmessageid"); }
	set { this.SetPropertyValue<EntityReference>("sdkmessageid", value, "sdkmessageid"); }
}
///<summary>
///<para>Logical Name: sdkmessageprocessingstepsecureconfigid</para>
///</summary>
[AttributeLogicalNameAttribute("sdkmessageprocessingstepsecureconfigid")]
public EntityReference sdkmessageprocessingstepsecureconfigid
{
	get { return this.GetPropertyValue<EntityReference>("sdkmessageprocessingstepsecureconfigid"); }
	set { this.SetPropertyValue<EntityReference>("sdkmessageprocessingstepsecureconfigid", value, "sdkmessageprocessingstepsecureconfigid"); }
}
///<summary>
///<para>Logical Name: sdkmessagefilterid</para>
///</summary>
[AttributeLogicalNameAttribute("sdkmessagefilterid")]
public EntityReference sdkmessagefilterid
{
	get { return this.GetPropertyValue<EntityReference>("sdkmessagefilterid"); }
	set { this.SetPropertyValue<EntityReference>("sdkmessagefilterid", value, "sdkmessagefilterid"); }
}
///<summary>
///<para>Logical Name: supportingsolutionid</para>
///</summary>
[AttributeLogicalNameAttribute("supportingsolutionid")]
public Guid supportingsolutionid
{
	get { return this.GetPropertyValue<Guid>("supportingsolutionid"); }
}
///<summary>
///<para>Logical Name: solutionid</para>
///</summary>
[AttributeLogicalNameAttribute("solutionid")]
public Guid solutionid
{
	get { return this.GetPropertyValue<Guid>("solutionid"); }
}
///<summary>
///<para>Logical Name: ismanaged</para>
///<para>True = Managed</para>
///<para>False = Unmanaged</para>
///</summary>
[AttributeLogicalNameAttribute("ismanaged")]
public bool? ismanaged
{
	get { return this.GetPropertyValue<bool?>("ismanaged"); }
}
/// <summary>
///Logical Name: statecode
/// </summary>
[AttributeLogicalNameAttribute("statecode")]
public eStatus? statecode
{
	get
	{
		if (statecode_OptionSetValue != null) { return (eStatus)statecode_OptionSetValue.Value; }
		return null;
	}
	set
	{
		if (value != null) { this.statecode_OptionSetValue = new OptionSetValue((int)value); }
		else this.statecode_OptionSetValue = null;
	}
}
///<summary>
///<para>Logical Name: statecode</para>
///</summary>
[AttributeLogicalNameAttribute("statecode")]
public OptionSetValue statecode_OptionSetValue
{
	get { return this.GetPropertyValue<OptionSetValue>("statecode"); }
	set { this.SetPropertyValue<OptionSetValue>("statecode", value, "statecode_OptionSetValue"); }
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="Service">CRM Organization Service</param>
/// <returns></returns>
public string statecode_Text(IOrganizationService Service)
{
	return this.statecode_OptionSetValue.GetOptionSetText(Service, this, "statecode");
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
/// <returns></returns>
public string statecode_Text(EnumAttributeMetadata AttributeMetadata)
{
	return AttributeMetadata.GetOptionSetText(this.statecode_OptionSetValue.Value);
}
/// <summary>
///Logical Name: statuscode
/// </summary>
[AttributeLogicalNameAttribute("statuscode")]
public eStatusReason? statuscode
{
	get
	{
		if (statuscode_OptionSetValue != null) { return (eStatusReason)statuscode_OptionSetValue.Value; }
		return null;
	}
	set
	{
		if (value != null) { this.statuscode_OptionSetValue = new OptionSetValue((int)value); }
		else this.statuscode_OptionSetValue = null;
	}
}
///<summary>
///<para>Logical Name: statuscode</para>
///</summary>
[AttributeLogicalNameAttribute("statuscode")]
public OptionSetValue statuscode_OptionSetValue
{
	get { return this.GetPropertyValue<OptionSetValue>("statuscode"); }
	set { this.SetPropertyValue<OptionSetValue>("statuscode", value, "statuscode_OptionSetValue"); }
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="Service">CRM Organization Service</param>
/// <returns></returns>
public string statuscode_Text(IOrganizationService Service)
{
	return this.statuscode_OptionSetValue.GetOptionSetText(Service, this, "statuscode");
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
/// <returns></returns>
public string statuscode_Text(EnumAttributeMetadata AttributeMetadata)
{
	return AttributeMetadata.GetOptionSetText(this.statuscode_OptionSetValue.Value);
}


        /// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: SdkMessageProcessingStep_AsyncOperations</para>
/// </summary>
public List<Entity> SdkMessageProcessingStep_AsyncOperations (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "asyncoperation", "owningextensionid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: SdkMessageProcessingStep_AsyncOperations</para>
/// </summary>
public List<Entity> SdkMessageProcessingStep_AsyncOperations (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "asyncoperation", "owningextensionid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: sdkmessageprocessingstepid_sdkmessageprocessingstepimage</para>
/// </summary>
public List<Entity> sdkmessageprocessingstepid_sdkmessageprocessingstepimage (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "sdkmessageprocessingstepimage", "sdkmessageprocessingstepid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: sdkmessageprocessingstepid_sdkmessageprocessingstepimage</para>
/// </summary>
public List<Entity> sdkmessageprocessingstepid_sdkmessageprocessingstepimage (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "sdkmessageprocessingstepimage", "sdkmessageprocessingstepid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: userentityinstancedata_sdkmessageprocessingstep</para>
/// </summary>
public List<Entity> userentityinstancedata_sdkmessageprocessingstep (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "userentityinstancedata", "objectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: userentityinstancedata_sdkmessageprocessingstep</para>
/// </summary>
public List<Entity> userentityinstancedata_sdkmessageprocessingstep (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "userentityinstancedata", "objectid", Columns); }


        

        

        public enum eComponentState
{
	///<summary><para>Published</para>
	///<para>Value = 0</para></summary>
	[Description("Published")]
	Published = 0, 
	///<summary><para>Unpublished</para>
	///<para>Value = 1</para></summary>
	[Description("Unpublished")]
	Unpublished = 1, 
	///<summary><para>Deleted</para>
	///<para>Value = 2</para></summary>
	[Description("Deleted")]
	Deleted = 2, 
	///<summary><para>Deleted Unpublished</para>
	///<para>Value = 3</para></summary>
	[Description("Deleted Unpublished")]
	DeletedUnpublished = 3
}
public enum eSupportedDeployment
{
	///<summary><para>Server Only</para>
	///<para>Value = 0</para></summary>
	[Description("Server Only")]
	ServerOnly = 0, 
	///<summary><para>Microsoft Dynamics CRM Client for Outlook Only</para>
	///<para>Value = 1</para></summary>
	[Description("Microsoft Dynamics CRM Client for Outlook Only")]
	MicrosoftDynamicsCRMClientForOutlookOnly = 1, 
	///<summary><para>Both</para>
	///<para>Value = 2</para></summary>
	[Description("Both")]
	Both = 2
}
public enum eMode
{
	///<summary><para>Synchronous</para>
	///<para>Value = 0</para></summary>
	[Description("Synchronous")]
	Synchronous = 0, 
	///<summary><para>Asynchronous</para>
	///<para>Value = 1</para></summary>
	[Description("Asynchronous")]
	Asynchronous = 1
}
public enum eStage
{
	///<summary><para>Initial Pre-operation (For internal use only)</para>
	///<para>Value = 5</para></summary>
	[Description("Initial Pre-operation (For internal use only)")]
	InitialPre_operation_ForInternalUseOnly = 5, 
	///<summary><para>Pre-validation</para>
	///<para>Value = 10</para></summary>
	[Description("Pre-validation")]
	Pre_validation = 10, 
	///<summary><para>Internal Pre-operation Before External Plugins (For internal use only)</para>
	///<para>Value = 15</para></summary>
	[Description("Internal Pre-operation Before External Plugins (For internal use only)")]
	InternalPre_operationBeforeExternalPlugins_ForInternalUseOnly = 15, 
	///<summary><para>Pre-operation</para>
	///<para>Value = 20</para></summary>
	[Description("Pre-operation")]
	Pre_operation = 20, 
	///<summary><para>Internal Pre-operation After External Plugins (For internal use only)</para>
	///<para>Value = 25</para></summary>
	[Description("Internal Pre-operation After External Plugins (For internal use only)")]
	InternalPre_operationAfterExternalPlugins_ForInternalUseOnly = 25, 
	///<summary><para>Main Operation (For internal use only)</para>
	///<para>Value = 30</para></summary>
	[Description("Main Operation (For internal use only)")]
	MainOperation_ForInternalUseOnly = 30, 
	///<summary><para>Internal Post-operation Before External Plugins (For internal use only)</para>
	///<para>Value = 35</para></summary>
	[Description("Internal Post-operation Before External Plugins (For internal use only)")]
	InternalPost_operationBeforeExternalPlugins_ForInternalUseOnly = 35, 
	///<summary><para>Post-operation</para>
	///<para>Value = 40</para></summary>
	[Description("Post-operation")]
	Post_operation = 40, 
	///<summary><para>Internal Post-operation After External Plugins (For internal use only)</para>
	///<para>Value = 45</para></summary>
	[Description("Internal Post-operation After External Plugins (For internal use only)")]
	InternalPost_operationAfterExternalPlugins_ForInternalUseOnly = 45, 
	///<summary><para>Post-operation (Deprecated)</para>
	///<para>Value = 50</para></summary>
	[Description("Post-operation (Deprecated)")]
	Post_operation_Deprecated = 50, 
	///<summary><para>Final Post-operation (For internal use only)</para>
	///<para>Value = 55</para></summary>
	[Description("Final Post-operation (For internal use only)")]
	FinalPost_operation_ForInternalUseOnly = 55
}
public enum eInvocationSource
{
	///<summary><para>Internal</para>
	///<para>Value = -1</para></summary>
	[Description("Internal")]
	@Internal = -1, 
	///<summary><para>Parent</para>
	///<para>Value = 0</para></summary>
	[Description("Parent")]
	Parent = 0, 
	///<summary><para>Child</para>
	///<para>Value = 1</para></summary>
	[Description("Child")]
	Child = 1
}
public enum eStatus
{
	///<summary><para>Enabled</para>
	///<para>Value = 0</para></summary>
	[Description("Enabled")]
	Enabled = 0, 
	///<summary><para>Disabled</para>
	///<para>Value = 1</para></summary>
	[Description("Disabled")]
	Disabled = 1
}
public enum eStatusReason
{
	///<summary><para>Enabled</para>
	///<para>Value = 1</para></summary>
	[Description("Enabled")]
	Enabled_Enabled = 1, 
	///<summary><para>Disabled</para>
	///<para>Value = 2</para></summary>
	[Description("Disabled")]
	Disabled_Disabled = 2
}
public void SetState(IOrganizationService Service, eStatus State, eStatusReason Status)
{
	Service.SetState(this, (int)State, (int)Status);
}
public async System.Threading.Tasks.Task SetStateAsync(IOrganizationService Service, eStatus State, eStatusReason Status)
{
	 await Service.SetStateAsync(this, (int)State, (int)Status);
}


        public static class Properties
{
	/// <summary><para>createdonbehalfbyyominame</para>
	/// <para>createdonbehalfbyyominame</para></summary>
	public const string createdonbehalfbyyominame = "createdonbehalfbyyominame";
	/// <summary><para>eventhandlertypecode</para>
	/// <para>eventhandlertypecode</para></summary>
	public const string eventhandlertypecode = "eventhandlertypecode";
	/// <summary><para>eventhandlername</para>
	/// <para>eventhandlername</para></summary>
	public const string eventhandlername = "eventhandlername";
	/// <summary><para>impersonatinguseridname</para>
	/// <para>impersonatinguseridname</para></summary>
	public const string impersonatinguseridname = "impersonatinguseridname";
	/// <summary><para>customizationlevel</para>
	/// <para>customizationlevel</para></summary>
	public const string customizationlevel = "customizationlevel";
	/// <summary><para>modifiedbyname</para>
	/// <para>modifiedbyname</para></summary>
	public const string modifiedbyname = "modifiedbyname";
	/// <summary><para>versionnumber</para>
	/// <para>versionnumber</para></summary>
	public const string versionnumber = "versionnumber";
	/// <summary><para>sdkmessageprocessingstepid</para>
	/// <para>sdkmessageprocessingstepid</para></summary>
	public const string sdkmessageprocessingstepid = "sdkmessageprocessingstepid";
	/// <summary><para>sdkmessageidname</para>
	/// <para>sdkmessageidname</para></summary>
	public const string sdkmessageidname = "sdkmessageidname";
	/// <summary><para>createdbyname</para>
	/// <para>createdbyname</para></summary>
	public const string createdbyname = "createdbyname";
	/// <summary><para>modifiedonbehalfbyyominame</para>
	/// <para>modifiedonbehalfbyyominame</para></summary>
	public const string modifiedonbehalfbyyominame = "modifiedonbehalfbyyominame";
	/// <summary><para>organizationid</para>
	/// <para>organizationid</para></summary>
	public const string organizationid = "organizationid";
	/// <summary><para>createdonbehalfbyname</para>
	/// <para>createdonbehalfbyname</para></summary>
	public const string createdonbehalfbyname = "createdonbehalfbyname";
	/// <summary><para>sdkmessageprocessingstepidunique</para>
	/// <para>sdkmessageprocessingstepidunique</para></summary>
	public const string sdkmessageprocessingstepidunique = "sdkmessageprocessingstepidunique";
	/// <summary><para>modifiedonbehalfbyname</para>
	/// <para>modifiedonbehalfbyname</para></summary>
	public const string modifiedonbehalfbyname = "modifiedonbehalfbyname";
	/// <summary><para>plugintypeidname</para>
	/// <para>plugintypeidname</para></summary>
	public const string plugintypeidname = "plugintypeidname";
	/// <summary><para>Asynchronous Automatic Delete</para>
	/// <para>asyncautodelete</para></summary>
	public const string asyncautodelete = "asyncautodelete";
	/// <summary><para>Component State</para>
	/// <para>componentstate</para></summary>
	public const string componentstate = "componentstate";
	/// <summary><para>Configuration</para>
	/// <para>configuration</para></summary>
	public const string configuration = "configuration";
	/// <summary><para>Created By</para>
	/// <para>createdby</para></summary>
	public const string createdby = "createdby";
	/// <summary><para>Created By (Delegate)</para>
	/// <para>createdonbehalfby</para></summary>
	public const string createdonbehalfby = "createdonbehalfby";
	/// <summary><para>Created On</para>
	/// <para>createdon</para></summary>
	public const string createdon = "createdon";
	/// <summary><para>Customizable</para>
	/// <para>iscustomizable</para></summary>
	public const string iscustomizable = "iscustomizable";
	/// <summary><para>Deployment</para>
	/// <para>supporteddeployment</para></summary>
	public const string supporteddeployment = "supporteddeployment";
	/// <summary><para>Description</para>
	/// <para>description</para></summary>
	public const string description = "description";
	/// <summary><para>Event Handler</para>
	/// <para>eventhandler</para></summary>
	public const string eventhandler = "eventhandler";
	/// <summary><para>Execution Mode</para>
	/// <para>mode</para></summary>
	public const string mode = "mode";
	/// <summary><para>Execution Order</para>
	/// <para>rank</para></summary>
	public const string rank = "rank";
	/// <summary><para>Execution Stage</para>
	/// <para>stage</para></summary>
	public const string stage = "stage";
	/// <summary><para>Filtering Attributes</para>
	/// <para>filteringattributes</para></summary>
	public const string filteringattributes = "filteringattributes";
	/// <summary><para>Hidden</para>
	/// <para>ishidden</para></summary>
	public const string ishidden = "ishidden";
	/// <summary><para>Impersonating User</para>
	/// <para>impersonatinguserid</para></summary>
	public const string impersonatinguserid = "impersonatinguserid";
	/// <summary><para>Intent</para>
	/// <para>canusereadonlyconnection</para></summary>
	public const string canusereadonlyconnection = "canusereadonlyconnection";
	/// <summary><para>Introduced Version</para>
	/// <para>introducedversion</para></summary>
	public const string introducedversion = "introducedversion";
	/// <summary><para>Invocation Source</para>
	/// <para>invocationsource</para></summary>
	public const string invocationsource = "invocationsource";
	/// <summary><para>Modified By</para>
	/// <para>modifiedby</para></summary>
	public const string modifiedby = "modifiedby";
	/// <summary><para>Modified By (Delegate)</para>
	/// <para>modifiedonbehalfby</para></summary>
	public const string modifiedonbehalfby = "modifiedonbehalfby";
	/// <summary><para>Modified On</para>
	/// <para>modifiedon</para></summary>
	public const string modifiedon = "modifiedon";
	/// <summary><para>Name</para>
	/// <para>name</para></summary>
	public const string name = "name";
	/// <summary><para>Plug-In Type</para>
	/// <para>plugintypeid</para></summary>
	public const string plugintypeid = "plugintypeid";
	/// <summary><para>Record Overwrite Time</para>
	/// <para>overwritetime</para></summary>
	public const string overwritetime = "overwritetime";
	/// <summary><para>SDK Message</para>
	/// <para>sdkmessageid</para></summary>
	public const string sdkmessageid = "sdkmessageid";
	/// <summary><para>SDK Message Processing Step Secure Configuration</para>
	/// <para>sdkmessageprocessingstepsecureconfigid</para></summary>
	public const string sdkmessageprocessingstepsecureconfigid = "sdkmessageprocessingstepsecureconfigid";
	/// <summary><para>SdkMessage Filter</para>
	/// <para>sdkmessagefilterid</para></summary>
	public const string sdkmessagefilterid = "sdkmessagefilterid";
	/// <summary><para>Solution</para>
	/// <para>supportingsolutionid</para></summary>
	public const string supportingsolutionid = "supportingsolutionid";
	/// <summary><para>Solution</para>
	/// <para>solutionid</para></summary>
	public const string solutionid = "solutionid";
	/// <summary><para>State</para>
	/// <para>ismanaged</para></summary>
	public const string ismanaged = "ismanaged";
	/// <summary><para>Status</para>
	/// <para>statecode</para></summary>
	public const string statecode = "statecode";
	/// <summary><para>Status Reason</para>
	/// <para>statuscode</para></summary>
	public const string statuscode = "statuscode";
}

    }
}
